### ISSUE TITLE
Dead Dork

### ISSUE THREAD

**Issue by sanmarg** [sushiwushi/bug-bounty-dorks#13]
Dear Team,
I have found that  "powered by hackerone" "submit vulnerability report" dork which is listed on 34th line, does not work now meaning that it does not give hackerone programs or any bug bounty or responsible disclosure programs. The dork only shows websites where the dork is listed as  to find programs .
Since, its dead now so it should be removed.

**Comment by sushiwushi** [comment]
Removed, thanks!
